name: Generate Snake Animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Generate the snake files in github folder
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: upethalaksiluni
          outputs: |
            github/snake.svg
            github/snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create github directory if it doesn't exist and commit files
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Create github directory if it doesn't exist
          mkdir -p github
          
          # Add the files
          git add github/snake.svg github/snake-dark.svg
          
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update snake animation"
            git push
          else
            echo "No changes to commit"
          fi
